TaskbarProgress: True              # True or False                                             # Whether the taskbar will show the song progress
RefreshRate: 30                    # RefreshRate >= 1 and RefreshRate <= 1000                  # How many times a second the visual updates
CenterIndicators: False            # True or False                                             # Whether lines should be drawn for the center of panpot in the visual
PanpotIndicators: False            # True or False                                             # Whether lines should be drawn for the track's panpot in the visual
PlaylistMode: "Random"             # "Random" or "Sequential"                                  # The way the playlist will behave
PlaylistSongLoops: 0               # Loops >= 0 and Loops <= 9223372036854775807               # How many times a song should loop before fading out
PlaylistFadeOutMilliseconds: 10000 # Milliseconds >= 0 and Milliseconds <= 9223372036854775807 # How many milliseconds it should take to fade out of a song
MiddleCOctave: 4                   # Octave >= --128 and Octave <= 127                         # The octave that holds middle C. Used in the visual and track viewer
Colors:
  0: {H: 185, S: 240, L: 180}
  1: {H: 183, S: 240, L: 170}
  2: {H: 180, S: 240, L: 157}
  3: {H: 184, S: 240, L: 85}
  4: {H: 171, S: 240, L: 134}
  5: {H: 168, S: 240, L: 159}
  6: {H: 36, S: 240, L: 170}
  7: {H: 15, S: 240, L: 134}
  8: {H: 175, S: 240, L: 200}
  9: {H: 120, S: 240, L: 150}
  10: {H: 114, S: 240, L: 138}
  11: {H: 99, S: 240, L: 171}
  12: {H: 68, S: 240, L: 171}
  13: {H: 83, S: 240, L: 200}
  14: {H: 215, S: 240, L: 104}
  15: {H: 25, S: 240, L: 200}
  16: {H: 224, S: 240, L: 150}
  17: {H: 195, S: 240, L: 120}
  18: {H: 206, S: 240, L: 95}
  19: {H: 218, S: 240, L: 129}
  20: {H: 203, S: 240, L: 180}
  21: {H: 145, S: 240, L: 100}
  22: {H: 140, S: 240, L: 111}
  23: {H: 151, S: 240, L: 120}
  24: {H: 5, S: 240, L: 169}
  25: {H: 6, S: 240, L: 156}
  26: {H: 14, S: 240, L: 164}
  27: {H: 12, S: 240, L: 137}
  28: {H: 8, S: 240, L: 140}
  29: {H: 0, S: 240, L: 123}
  30: {H: 229, S: 240, L: 70}
  31: {H: 239, S: 240, L: 89}
  32: {H: 25, S: 180, L: 160}
  33: {H: 20, S: 180, L: 145}
  34: {H: 17, S: 180, L: 140}
  35: {H: 36, S: 240, L: 163}
  36: {H: 25, S: 180, L: 140}
  37: {H: 25, S: 210, L: 95}
  38: {H: 160, S: 0, L: 180}
  39: {H: 200, S: 240, L: 90}
  40: {H: 195, S: 240, L: 100}
  41: {H: 190, S: 240, L: 93}
  42: {H: 180, S: 240, L: 90}
  43: {H: 170, S: 240, L: 150}
  44: {H: 166, S: 240, L: 89}
  45: {H: 210, S: 240, L: 170}
  46: {H: 214, S: 240, L: 185}
  47: {H: 15, S: 135, L: 135}
  48: {H: 148, S: 240, L: 130}
  49: {H: 173, S: 240, L: 80}
  50: {H: 170, S: 240, L: 95}
  51: {H: 176, S: 240, L: 100}
  52: {H: 26, S: 240, L: 215}
  53: {H: 20, S: 240, L: 210}
  54: {H: 5, S: 240, L: 220}
  55: {H: 6, S: 240, L: 150}
  56: {H: 22, S: 240, L: 134}
  57: {H: 25, S: 240, L: 130}
  58: {H: 40, S: 240, L: 120}
  59: {H: 28, S: 240, L: 122}
  60: {H: 16, S: 240, L: 124}
  61: {H: 11, S: 240, L: 118}
  62: {H: 53, S: 240, L: 158}
  63: {H: 57, S: 240, L: 133}
  64: {H: 30, S: 240, L: 195}
  65: {H: 23, S: 240, L: 182}
  66: {H: 32, S: 240, L: 160}
  67: {H: 32, S: 240, L: 130}
  68: {H: 37, S: 240, L: 135}
  69: {H: 13, S: 240, L: 143}
  70: {H: 134, S: 240, L: 85}
  71: {H: 130, S: 240, L: 95}
  72: {H: 120, S: 240, L: 165}
  73: {H: 126, S: 240, L: 120}
  74: {H: 126, S: 240, L: 100}
  75: {H: 135, S: 240, L: 160}
  76: {H: 118, S: 240, L: 186}
  77: {H: 135, S: 240, L: 102}
  78: {H: 113, S: 240, L: 100}
  79: {H: 70, S: 240, L: 160}
  80: {H: 82, S: 240, L: 132}
  81: {H: 227, S: 240, L: 188}
  82: {H: 103, S: 240, L: 140}
  83: {H: 60, S: 240, L: 165}
  84: {H: 239, S: 240, L: 165}
  85: {H: 123, S: 240, L: 175}
  86: {H: 210, S: 240, L: 145}
  87: {H: 53, S: 240, L: 120}
  88: {H: 110, S: 240, L: 155}
  89: {H: 122, S: 240, L: 205}
  90: {H: 217, S: 240, L: 95}
  91: {H: 142, S: 240, L: 50}
  92: {H: 100, S: 240, L: 90}
  93: {H: 137, S: 240, L: 90}
  94: {H: 188, S: 240, L: 117}
  95: {H: 160, S: 240, L: 210}
  96: {H: 130, S: 240, L: 200}
  97: {H: 202, S: 240, L: 80}
  98: {H: 0, S: 240, L: 160}
  99: {H: 30, S: 240, L: 110}
  100: {H: 130, S: 240, L: 210}
  101: {H: 75, S: 240, L: 75}
  102: {H: 180, S: 240, L: 205}
  103: {H: 27, S: 200, L: 105}
  104: {H: 33, S: 200, L: 145}
  105: {H: 37, S: 220, L: 130}
  106: {H: 45, S: 240, L: 135}
  107: {H: 55, S: 240, L: 175}
  108: {H: 95, S: 240, L: 185}
  109: {H: 53, S: 240, L: 190}
  110: {H: 135, S: 240, L: 120}
  111: {H: 38, S: 240, L: 110}
  112: {H: 220, S: 240, L: 170}
  113: {H: 120, S: 80, L: 150}
  114: {H: 130, S: 120, L: 190}
  115: {H: 0, S: 80, L: 90}
  116: {H: 18, S: 125, L: 130}
  117: {H: 15, S: 70, L: 120}
  118: {H: 200, S: 80, L: 110}
  119: {H: 140, S: 60, L: 180}
  120: {H: 10, S: 240, L: 90}
  121: {H: 123, S: 156, L: 100}
  122: {H: 128, S: 240, L: 100}
  123: {H: 40, S: 240, L: 180}
  124: {H: 239, S: 200, L: 90}
  125: {H: 145, S: 10, L: 155}
  126: {H: 15, S: 80, L: 160}
  127: {H: 160, S: 80, L: 150}